# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
sudo: required
cache: packages


install:
  - Rscript -e "install.packages(c( 'devtools', 'roxygen2', 'testthat', 'knitr', 'rmarkdown', 'Rcpp', 'RcppArmadillo', 'R6', 'covr' ), repos =  'https://cloud.r-project.org/' )"
  

after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'


notifications:
  email:
    on_success: change
    on_failure: change

