# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
sudo: required
cache: packages

os:
  - linux

compiler:
  - gcc

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    #- CFLAGS="-std=c99 -Wall -pedantic"

before_install:

  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc g++
  - sudo apt-get -qq install libgit2-dev
  - sudo apt-get install libgfortran3
  - sudo apt-get install r-base-dev
  - sudo apt-get install libarmadillo-dev
  - sudo apt-get install libopenblas-dev
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install libarpack++2-dev
  - sudo apt-get install gfortran
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so
  - sudo apt-get -qq update


r_packages:
  - devtools
  - roxygen2
  - testthat
  - knitr
  - rmarkdown
  - Rcpp
  - RcppArmadillo
  - R6
  - covr


after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change

