# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

export_From_geojson <- function(input_file, flatten_coords = FALSE, average_coordinates = FALSE) {
    .Call('geojsonR_export_From_geojson', PACKAGE = 'geojsonR', input_file, flatten_coords, average_coordinates)
}

export_From_JSON <- function(input_file) {
    .Call('geojsonR_export_From_JSON', PACKAGE = 'geojsonR', input_file)
}

dump_geojson <- function(input_data) {
    .Call('geojsonR_dump_geojson', PACKAGE = 'geojsonR', input_data)
}

Features_TO_Collection <- function(feat_files_lst, bbox_vec) {
    .Call('geojsonR_Features_TO_Collection', PACKAGE = 'geojsonR', feat_files_lst, bbox_vec)
}

export_To_GeoJson <- function(geometry_object, data_POINTS, data_ARRAYS, data_ARRAY_ARRAYS, data_POLYGON_ARRAYS, stringify = FALSE) {
    .Call('geojsonR_export_To_GeoJson', PACKAGE = 'geojsonR', geometry_object, data_POINTS, data_ARRAYS, data_ARRAY_ARRAYS, data_POLYGON_ARRAYS, stringify)
}

Geom_Collection <- function(geometry_object_names, geometry_objects, stringify = FALSE) {
    .Call('geojsonR_Geom_Collection', PACKAGE = 'geojsonR', geometry_object_names, geometry_objects, stringify)
}

Feature_Obj <- function(geometry_object_names, geometry_objects, stringify = FALSE) {
    .Call('geojsonR_Feature_Obj', PACKAGE = 'geojsonR', geometry_object_names, geometry_objects, stringify)
}

Feature_collection_Obj <- function(geometry_object_names, geometry_objects, stringify = FALSE) {
    .Call('geojsonR_Feature_collection_Obj', PACKAGE = 'geojsonR', geometry_object_names, geometry_objects, stringify)
}

