# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

export_From_geojson <- function(input_file, flatten_coords = FALSE, average_coordinates = FALSE, to_list = FALSE) {
    .Call(`_geojsonR_export_From_geojson`, input_file, flatten_coords, average_coordinates, to_list)
}

export_From_JSON <- function(input_file) {
    .Call(`_geojsonR_export_From_JSON`, input_file)
}

dump_geojson <- function(input_data) {
    .Call(`_geojsonR_dump_geojson`, input_data)
}

Features_TO_Collection <- function(feat_files_lst, bbox_vec, verbose = FALSE) {
    .Call(`_geojsonR_Features_TO_Collection`, feat_files_lst, bbox_vec, verbose)
}

export_From_geojson_schema <- function(input_file, GEOMETRY_OBJECT_NAME = "", average_coordinates = FALSE, to_list = FALSE) {
    .Call(`_geojsonR_export_From_geojson_schema`, input_file, GEOMETRY_OBJECT_NAME, average_coordinates, to_list)
}

list_files <- function(path, full_path = TRUE) {
    .Call(`_geojsonR_list_files`, path, full_path)
}

merge_json <- function(input_folder, output_file, concat_delimiter = "\n", verbose = FALSE) {
    invisible(.Call(`_geojsonR_merge_json`, input_folder, output_file, concat_delimiter, verbose))
}

DATA_TYPE <- function(sublist) {
    .Call(`_geojsonR_DATA_TYPE`, sublist)
}

inner_coords <- function(geom_lst, z, polygon_interior = FALSE) {
    .Call(`_geojsonR_inner_coords`, geom_lst, z, polygon_interior)
}

Polygon_with_interior_rings <- function(geom_lst, i, verbose) {
    .Call(`_geojsonR_Polygon_with_interior_rings`, geom_lst, i, verbose)
}

SAVE_R_list_Features_2_FeatureCollection <- function(x, path_to_file = "", verbose = FALSE) {
    .Call(`_geojsonR_SAVE_R_list_Features_2_FeatureCollection`, x, path_to_file, verbose)
}

export_To_GeoJson <- function(geometry_object, data_POINTS, data_ARRAYS, data_ARRAY_ARRAYS, data_POLYGON_ARRAYS, stringify = FALSE) {
    .Call(`_geojsonR_export_To_GeoJson`, geometry_object, data_POINTS, data_ARRAYS, data_ARRAY_ARRAYS, data_POLYGON_ARRAYS, stringify)
}

Geom_Collection <- function(geometry_object_names, geometry_objects, stringify = FALSE) {
    .Call(`_geojsonR_Geom_Collection`, geometry_object_names, geometry_objects, stringify)
}

Feature_Obj <- function(geometry_object_names, geometry_objects, stringify = FALSE) {
    .Call(`_geojsonR_Feature_Obj`, geometry_object_names, geometry_objects, stringify)
}

Feature_collection_Obj <- function(geometry_object_names, geometry_objects, stringify = FALSE) {
    .Call(`_geojsonR_Feature_collection_Obj`, geometry_object_names, geometry_objects, stringify)
}

